Provider Pictogromas, Rutas con Argumentos y mejora de diseño
Hope-uni/hope.app pull request #23
Opened 2024-04-12 05:38 UTC by LordMario

## Description
* Implementacion de provider para la lista de pictogramas
* Refactorizacion de inputs y selectBox para uso de maneja generica
* Agregando rutas para la pantalla de child y lista de pictogramas con argumento(Data)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

Describe the tests you've run to verify the changes. Provide instructions for reproduction and indicate any relevant details for your test setup.

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [ ] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [x] I have reviewed my code and corrected any spelling mistakes.

2024-04-12 23:49 UTC, SamBarFu requested changes

2024-04-12 23:49 UTC, SamBarFu commented on lib/presentation/pages/children/childs_data.page.dart
Cambiar el nombre del archivo

2024-04-12 23:49 UTC, SamBarFu commented on lib/presentation/pages/pictogram/pictogram.page.dart
>          loadNextImages: () => print('cargando nuevas imagenes'),
agregar internacionalización

2024-04-12 23:55 UTC, LordMario commented on lib/presentation/pages/pictogram/pictogram.page.dart
>          loadNextImages: () => print('cargando nuevas imagenes'),
Eso es una función de prueba, arriba hay un comentario que se debe de quitar cuando este listo el endpoint, no se ve el comentario porque no es un cambio en el commit

2024-04-13 02:19 UTC, LordMario commented on lib/presentation/pages/children/childs_data.page.dart
Listo

2024-04-13 02:52 UTC, SamBarFu approved these changes

2024-04-16 02:05 UTC, merged