Implementado diseño y provider para el listado de actividades
Hope-uni/hope.app pull request #30
Opened 2024-04-22 22:01 UTC by LordMario

## Description
* Implementando diseño del listado de actividades
* Implementando provider para el listado de actividades

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

Describe the tests you've run to verify the changes. Provide instructions for reproduction and indicate any relevant details for your test setup.

![g](https://github.com/Hope-uni/hope.app/assets/37022613/7ecf5780-50f6-4f82-84b2-689f4adfad2a)
![gg](https://github.com/Hope-uni/hope.app/assets/37022613/1b1fdb66-ec7d-4db0-8cc4-7f0ff5be475a)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [x] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [x] I have reviewed my code and corrected any spelling mistakes.

2024-04-22 23:24 UTC, SamBarFu requested changes

2024-04-22 23:24 UTC, SamBarFu commented on lib/generated/intl/messages_en.dart
> +            MessageLookupByLibrary.simpleMessage("Crear nuevas actividades"),
Porqué esta en plural? acaso se van a crear varias actividades de un solo?

2024-04-22 23:24 UTC, SamBarFu commented on lib/generated/intl/messages_en.dart
> +        "Pagina": MessageLookupByLibrary.simpleMessage("Pagina"),
Tildar palabra

2024-04-22 23:24 UTC, SamBarFu commented on lib/generated/intl/messages_es_NI.dart
> +        "Pagina": MessageLookupByLibrary.simpleMessage("Pagina"),
Tildar palabra

2024-04-23 04:11 UTC, LordMario commented on lib/generated/intl/messages_en.dart
> +            MessageLookupByLibrary.simpleMessage("Crear nuevas actividades"),
Listo

2024-04-23 04:12 UTC, LordMario commented on lib/generated/intl/messages_en.dart
> +        "Pagina": MessageLookupByLibrary.simpleMessage("Pagina"),
listo

2024-04-23 04:12 UTC, LordMario commented on lib/generated/intl/messages_es_NI.dart
> +        "Pagina": MessageLookupByLibrary.simpleMessage("Pagina"),
listo

2024-04-23 05:01 UTC, SamBarFu approved these changes

2024-04-24 15:59 UTC, SamBarFu requested changes
Cambiar de posición el botón de agregar actividades, a una parte más visible y accesible para el usuario.

2024-04-24 15:59 UTC, SamBarFu commented on lib/presentation/pages/activities/activities.page.dart
> +      drawer: const SideMenu(),
Este SideMenu se esta mandando en todas las pantallas? porque no crear un layout?

2024-04-26 00:55 UTC, SamBarFu approved these changes

2024-04-26 00:56 UTC, merged