Implementando modal para la confirmacion de eliminacion de actividad
Hope-uni/hope.app pull request #31
Opened 2024-04-26 04:53 UTC by LordMario

## Description
Se implemento el diseño del modal de confirmación de eliminación de la actividad al igual que se hicieron cambios en la interfaz del menu y el select del menu
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

![y](https://github.com/Hope-uni/hope.app/assets/37022613/9eba10b8-3499-4932-b7ec-2678d5681037)
![yy](https://github.com/Hope-uni/hope.app/assets/37022613/d16edbc1-3b8a-4878-ab92-87ab17fc3d0d)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [x] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [x] I have reviewed my code and corrected any spelling mistakes.

2024-04-29 15:14 UTC, SamBarFu requested changes

2024-04-29 15:14 UTC, SamBarFu commented on lib/presentation/utils/constants_menu.dart
>  final appMenuItemsDrawer = <MenuItem>[
Porque esta declaración de esta varaible esta diferente al resto?

más abajo tenes lo siguiente

final List<MenuItem> menuPacientTherapist = ...

Cuál es la diferencia de usar una o la otra?

2024-04-29 21:41 UTC, LordMario commented on lib/presentation/utils/constants_menu.dart
>  final appMenuItemsDrawer = <MenuItem>[
Si no comprendo mal la observación , siendo mas claro, no estoy indicando el tipo de datos como en los demás?
Si es eso , se corregirá en el próximo PR

2024-04-29 21:42 UTC, LordMario commented on lib/generated/intl/messages_en.dart
> +                "¿Esta seguro de eliminar permanentemente la actividad?"),
Se corregira en el proximo PR

2024-04-29 21:42 UTC, LordMario commented on lib/generated/intl/messages_es_NI.dart
> +                "¿Esta seguro de eliminar permanentemente la actividad?"),
Se corregira en el proximo PR

2024-04-30 15:59 UTC, SamBarFu approved these changes

2024-04-30 18:56 UTC, merged