Implementacion modal de contraseña y rediseño total de la APP
Hope-uni/hope.app pull request #32
Opened 2024-04-27 02:50 UTC by LordMario

## Description
* Implementacion de modal de cambio de contraseña
* Resediseño total de la App a modo vertical
  - Rediseño de pantallas de listados
  - Rediseño de las tablas
  - Rediseño de pantalla de informacion de los niños
  - Rediseño de pantalla del perfil
  - Rediseño del Login
  - Rediseño de pantalla de restablecer contraseña
  - Rediseño de pantalla de pictogramas

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

![a](https://github.com/Hope-uni/hope.app/assets/37022613/54661568-ed71-481b-b6df-4a27a2d2e2ae)
![aa](https://github.com/Hope-uni/hope.app/assets/37022613/45bde85b-102d-42d5-aa66-6aba52295b1b)
![aaa](https://github.com/Hope-uni/hope.app/assets/37022613/9a920131-13a2-4df2-b3d8-f94213c2fa77)
![aaaa](https://github.com/Hope-uni/hope.app/assets/37022613/eccd3893-c751-4ed1-9fcf-37d6feee2533)
![aaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/66f8adc6-cebc-46bf-8526-2780c0288d7a)
![aaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/1e9c41b3-fd14-45f7-913c-cb90fbdd22ad)
![aaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/8bb9d4f6-ce39-459f-a36d-471c0392b4ff)
![aaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/8e6da0fb-e4fa-4ca4-978a-b1b4b9808ef9)
![aaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/be2a71c2-498d-4637-898b-7c6cff38ac14)
![aaaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/a0041062-9271-4267-bb1a-36bd37d758ad)
![aaaaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/2d2f9edb-4fa6-4660-b312-62e79f8ae9d2)
![aaaaaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/2be79a36-51f6-4258-a8ad-4a5cec800fe4)
![aaaaaaaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/0e5f5409-93d5-491d-a197-3856a019e99b)
![aaaaaaaaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/96e7b1d3-be9d-4d7a-b48b-7452fa0790d3)
![aaaaaaaaaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/06e75335-74d8-46f6-aa5b-c91fd4e3125f)
![aaaaaaaaaaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/766ff552-31a6-4a29-8570-f04fa459446f)
![aaaaaaaaaaaaaaaaaa](https://github.com/Hope-uni/hope.app/assets/37022613/b9b87c14-cb99-475e-8213-f600e91104c2)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [x] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [x] I have reviewed my code and corrected any spelling mistakes.

2024-04-29 15:16 UTC, SamBarFu commented
![image](https://github.com/Hope-uni/hope.app/assets/50776023/1dc9d673-5d4e-44b3-83b2-ee7b6f118591)

cambiar de posición ese Iniciar Sesión, ponerlo debajo del botón enviar correo

2024-04-29 15:21 UTC, SamBarFu requested changes

2024-04-29 15:21 UTC, SamBarFu commented on android/app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait">
Porque estas cambiando esto aquí?

Este valor debería ser landscape por defecto, y cuando se identifique que es una pantalla de celular cambiar la orientación.

2024-04-29 21:45 UTC, LordMario commented on android/app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait">
Siguiendo esa lógica se puede hacer lo mismo al revez

2024-04-30 16:01 UTC, SamBarFu commented on android/app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait">
si, pero por defecto debería estar en landscape, no portrait, ya que el objetivo principal de la app es el tablero de comunicación, osea que la mayor parte del tiempo estará en landscape

2024-04-30 18:51 UTC, SamBarFu approved these changes

2024-04-30 18:55 UTC, merged