Implementando lógica y diseño para la creación, edición y visualización de actividades y Agregando name a las rutas
Hope-uni/hope.app pull request #34
Opened 2024-04-29 06:26 UTC by LordMario

## Description
* Implementando lógica y diseño para la creación, edición y visualización de actividades
* Agregando name a las rutas

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

![llll](https://github.com/Hope-uni/hope.app/assets/37022613/cd879e8b-ac7f-41ec-8ba8-64302ffe3037)
![lllll](https://github.com/Hope-uni/hope.app/assets/37022613/77f65417-cf52-48b7-ab61-d53e3922bc6f)
![llllll](https://github.com/Hope-uni/hope.app/assets/37022613/202f1a6e-e858-4421-a2c6-d12ac8940e9e)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [x] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [x] I have reviewed my code and corrected any spelling mistakes.

2024-04-29 15:33 UTC, SamBarFu commented
Las capturas son de una tablet, cuando sea la orientación de la app sea portrait mejor emular en dispositivos móviles y subir capturas con ese dispositivo

2024-04-29 15:36 UTC, SamBarFu requested changes

2024-04-29 15:36 UTC, SamBarFu commented on lib/presentation/pages/activities/new_activity.page.dart
> +                  title: '¡Guardado con exito!',
Corregir ortografía

2024-04-29 15:36 UTC, SamBarFu commented on lib/presentation/pages/activities/new_activity.page.dart
> +                          'Esta seguro de salir de la creacion de la actividad',
Esto es una pregunta, agregar signos de exclamación y corregir ortografía

2024-04-29 22:45 UTC, LordMario commented on lib/presentation/pages/activities/new_activity.page.dart
> +                  title: '¡Guardado con exito!',
Listo

2024-04-29 22:45 UTC, LordMario commented on lib/presentation/pages/activities/new_activity.page.dart
> +                          'Esta seguro de salir de la creacion de la actividad',
Listo

2024-04-30 16:03 UTC, SamBarFu approved these changes

2024-04-30 18:55 UTC, merged