Refactorizacion de la logica de redireccionamiento del menu
Hope-uni/hope.app pull request #36
Opened 2024-05-03 04:08 UTC by MarioRam0s

## Description
Se refactorizo la interfaz de menu y la logica de redireccionamiento para que sea mas eficiente

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [ ] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [x] I have reviewed my code and corrected any spelling mistakes.

2024-05-03 18:40 UTC, SamBarFu requested changes

2024-05-03 18:40 UTC, SamBarFu commented on lib/generated/intl/messages_en.dart
> +            "© 2024 Hope. All rights reserved"),
Que sea dinámico

2024-05-03 18:40 UTC, SamBarFu commented on lib/generated/intl/messages_es_NI.dart
> +            "© 2024 Hope. All rights reserved"),
Que sea dinámico

2024-05-03 21:22 UTC, MarioRam0s commented on lib/generated/intl/messages_en.dart
> +            "© 2024 Hope. All rights reserved"),
este cambio se subira en el ultimo PR

2024-05-03 21:22 UTC, MarioRam0s commented on lib/generated/intl/messages_es_NI.dart
> +            "© 2024 Hope. All rights reserved"),
este cambio se subira en el ultimo PR

2024-05-06 16:14 UTC, SamBarFu approved these changes

2024-05-07 00:20 UTC, merged