Mejora de diseño de la APP
Hope-uni/hope.app pull request #39
Opened 2024-05-07 02:58 UTC by MarioRam0s

## Description
* Mejora en la organización de los inputs de toda la APP
* Mejora general de toda la APP (Margin, colors)
* Agregando botón de clear al selectBoxCustom

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

![WhatsApp Image 2024-05-06 at 8 55 25 PM (3)](https://github.com/Hope-uni/hope.app/assets/37022613/ef453788-6577-4f6d-84ee-8d05f493d881)
![WhatsApp Image 2024-05-06 at 8 55 25 PM (4)](https://github.com/Hope-uni/hope.app/assets/37022613/78bf0028-3d00-4a40-9d6f-b5253e7b630f)
![WhatsApp Image 2024-05-06 at 8 55 25 PM (5)](https://github.com/Hope-uni/hope.app/assets/37022613/0639a803-10fc-47a0-8be7-d5771cb1ef4e)
![WhatsApp Image 2024-05-06 at 8 55 25 PM](https://github.com/Hope-uni/hope.app/assets/37022613/c40e7d0b-5ebe-48b4-90a7-a7d74b94ab3a)
![WhatsApp Image 2024-05-06 at 8 55 24 PM](https://github.com/Hope-uni/hope.app/assets/37022613/5545d16d-6bd7-4cc8-80db-21d84ceff1c8)
![WhatsApp Image 2024-05-06 at 8 55 25 PM (1)](https://github.com/Hope-uni/hope.app/assets/37022613/fa5012b2-11b1-4740-a1e1-2c34d6c88435)
![WhatsApp Image 2024-05-06 at 8 55 25 PM (2)](https://github.com/Hope-uni/hope.app/assets/37022613/fe35cb91-3f21-4bec-bb9a-ec9b9b508df3)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [x] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [x] I have reviewed my code and corrected any spelling mistakes.

2024-05-07 03:03 UTC, SamBarFu commented
Comentario

![image](https://github.com/Hope-uni/hope.app/assets/50776023/9021bd6a-37ee-4650-8940-b96408a91a4f)

Ya que solo es un solo tab, mejor quitarlo y agregar el titulo, o dejarlo como titulo, pero que no sea un tab.

2024-05-07 03:25 UTC, SamBarFu requested changes

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/activities/activities.page.dart
> +              label: 'Buscar por nombre de actividad',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/activities/activities.page.dart
> +                      title: 'Seleccionar 5 pictogramas de animales',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/activities/activities.page.dart
> +                      subTitle: 'Fase 4 | 20 puntos',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/activities/form_activity.dart
> +            label: 'Fase del autismo',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/activities/form_activity.dart
> +            label: 'Puntaje',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/activities/form_activity.dart
>                      'Seleccione pictogramas de la solucion',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/children/children.page.dart
> +              label: 'Buscar por primer nombre',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/children/children.page.dart
> +                      title: 'Mario Jose Ramos Mejia',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/pages/children/children.page.dart
> +                      subTitle: 'Fase 4 | 20 años',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/utils/modal_password.dart
> +                label: 'Contraseña actual',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/utils/modal_password.dart
> +                label: 'Nueva contraseña',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/utils/modal_password.dart
> +                label: 'Confirmar nueva contraseña',
agregar intl de una vez

2024-05-07 03:25 UTC, SamBarFu commented on lib/presentation/widgets/grid_images.dart
> +            hint: S.current.Categoria_de_pictogramas,
agregar intl de una vez

2024-05-07 06:23 UTC, MarioRam0s commented on lib/presentation/pages/activities/activities.page.dart
> +              label: 'Buscar por nombre de actividad',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:23 UTC, MarioRam0s commented on lib/presentation/pages/activities/activities.page.dart
> +                      title: 'Seleccionar 5 pictogramas de animales',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:23 UTC, MarioRam0s commented on lib/presentation/pages/activities/activities.page.dart
> +                      subTitle: 'Fase 4 | 20 puntos',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:23 UTC, MarioRam0s commented on lib/presentation/pages/activities/form_activity.dart
> +            label: 'Fase del autismo',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:24 UTC, MarioRam0s commented on lib/presentation/pages/activities/form_activity.dart
> +            label: 'Puntaje',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:24 UTC, MarioRam0s commented on lib/presentation/pages/children/children.page.dart
> +                      subTitle: 'Fase 4 | 20 años',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:24 UTC, MarioRam0s commented on lib/presentation/utils/modal_password.dart
> +                label: 'Contraseña actual',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:24 UTC, MarioRam0s commented on lib/presentation/utils/modal_password.dart
> +                label: 'Nueva contraseña',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:24 UTC, MarioRam0s commented on lib/presentation/utils/modal_password.dart
> +                label: 'Confirmar nueva contraseña',
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-07 06:24 UTC, MarioRam0s commented on lib/presentation/widgets/grid_images.dart
> +            hint: S.current.Categoria_de_pictogramas,
entendió, esos cambios se aplicaron en general en el ultimo PR Subido, y de igual manera se crearan las variables Intl en los PR correspondientes para futuro #40

2024-05-08 20:09 UTC, SamBarFu approved these changes

2024-05-09 08:22 UTC, merged