Implementando diseño de la pantalla del tablero de comunicación
Hope-uni/hope.app pull request #41
Opened 2024-05-09 08:27 UTC by MarioRam0s

## Description
* Implementando diseño de la pantalla del tablero de comunicación
* Creando widget para mostrar el progreso al presionar el botón

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

![WhatsApp Image 2024-05-09 at 2 12 20 AM](https://github.com/Hope-uni/hope.app/assets/37022613/32f20381-4f88-4c3e-92ac-10e59811c30d)
![i](https://github.com/Hope-uni/hope.app/assets/37022613/363d937a-6c27-44f9-96a2-390a66388140)
![ii](https://github.com/Hope-uni/hope.app/assets/37022613/0a6b8a95-9468-4290-81cf-4040e056d70d)
![iii](https://github.com/Hope-uni/hope.app/assets/37022613/a015d9f7-6288-4af0-b9fa-2945230611c5)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [x] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [x] I have reviewed my code and corrected any spelling mistakes.

2024-05-09 14:20 UTC, SamBarFu commented
![image](https://github.com/Hope-uni/hope.app/assets/50776023/fff12fb1-d53f-42aa-ab0f-ec822755de33)

la oración formada esta muy abajo casi no es visible. Hay que recordar que son niños con problemas cognitivos, entonces hay que ubicar un poco más visible y que sea más grande.

![image](https://github.com/Hope-uni/hope.app/assets/50776023/9b8f5dc4-2f36-4ec3-a55e-f9439b10b2d8)
podría colocarse por ahí

2024-05-09 21:47 UTC, SamBarFu requested changes

2024-05-09 23:59 UTC, MarioRam0s commented on lib/presentation/pages/board/board.page.dart
> +                'Actividad pendiente: Formar 5 oraciones con animales',
Se me escapo ese, listo

2024-05-10 03:18 UTC, SamBarFu approved these changes

2024-05-10 19:00 UTC, merged