DataSources y Respositories
Hope-uni/hope.app pull request #8
Opened 2024-03-12 05:39 UTC by LordMario

## Description
Aplicando datasources y repositories para la autenticación de usuarios y pequeña mejora en el diseño a la hora de mostrar el teclado

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] This change requires a documentation update
- [ ] Other (please describe): 

## How Has This Been Tested?

Describe the tests you've run to verify the changes. Provide instructions for reproduction and indicate any relevant details for your test setup.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in areas hard to understand.
- [ ] I have made the corresponding changes to the documentation.
- [x] My changes do not generate new warnings.
- [ ] I have added tests that prove my solution is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] All dependent changes have been merged and published in subsequent modules.
- [ ] I have reviewed my code and corrected any spelling mistakes.

2024-03-12 23:57 UTC, SamBarFu requested changes

2024-03-12 23:57 UTC, SamBarFu commented on lib/domain/datasources/auth.datasource.dart
> +  Future<User> resetPassword(String emailUser);
cambiar el nombre del parámetro por un nombre más descriptivo, emailOrUsername

2024-03-12 23:57 UTC, SamBarFu commented on lib/domain/repositories/auth.repository.dart
> +  Future<User> resetPassword(String emailUser);
cambiar el nombre del parámetro por un nombre más descriptivo, emailOrUsername

2024-03-12 23:57 UTC, SamBarFu commented on lib/infrastructure/datasources/auth.datasource.impl.dart
> +  Future<User> resetPassword(String emailUser) {
cambiar el nombre del parámetro por un nombre más descriptivo, emailOrUsername

2024-03-12 23:57 UTC, SamBarFu commented on lib/infrastructure/repositories/auth.repository.impl.dart
> +  Future<User> resetPassword(String emailUser) {
cambiar el nombre del parámetro por un nombre más descriptivo, emailOrUsername

2024-03-13 00:31 UTC, LordMario commented on lib/domain/repositories/auth.repository.dart
> +  Future<User> resetPassword(String emailUser);
Ese cambio de nombre del paramentro va en el proximo pr

2024-03-13 00:31 UTC, LordMario commented on lib/infrastructure/datasources/auth.datasource.impl.dart
> +  Future<User> resetPassword(String emailUser) {
Ese cambio de nombre del paramentro va en el proximo pr

2024-03-13 00:31 UTC, LordMario commented on lib/infrastructure/repositories/auth.repository.impl.dart
> +  Future<User> resetPassword(String emailUser) {
Ese cambio de nombre del paramentro va en el proximo pr

2024-03-13 01:09 UTC, LordMario commented on lib/domain/datasources/auth.datasource.dart
> +  Future<User> resetPassword(String emailUser);
listo , cambios realizados

2024-03-13 01:10 UTC, LordMario commented on lib/domain/repositories/auth.repository.dart
> +  Future<User> resetPassword(String emailUser);
listo , cambios realizados

2024-03-13 01:10 UTC, LordMario commented on lib/infrastructure/datasources/auth.datasource.impl.dart
> +  Future<User> resetPassword(String emailUser) {
listo , cambios realizados

2024-03-13 01:10 UTC, LordMario commented on lib/infrastructure/repositories/auth.repository.impl.dart
> +  Future<User> resetPassword(String emailUser) {
listo , cambios realizados

2024-03-13 01:10 UTC, SamBarFu approved these changes

2024-03-13 01:23 UTC, merged